Burnout-Devil/HacktoberFest-DSA2022

mergesort.py
Signed-off-by: Akash <107811139+Akash1437@users.noreply.github.com>
=> Created merge sort in python

Linked List/linked_list.c
Please accept my PR with all necessary hacktoberfest labels
Signed-off-by: amanydv72 <89766177+amanydv72@users.noreply.github.com>
=> All Operations of Linked list in c

addTwoNos.c
Signed-off-by: LostHeart-Gaming <116107285+LostHeart-Gaming@users.noreply.github.com>
=> Created add two numbers in c

linearSeach.c
Signed-off-by: LostHeart-Gaming <116107285+LostHeart-Gaming@users.noreply.github.com>
=> linear search in c

OperationOfStack.py
Signed-off-by: Razor-5 <116114456+Razor-5@users.noreply.github.com>
=> Created code to implement stack using list in python

DiamondPattern.py
Signed-off-by: Razor-5 <116114456+Razor-5@users.noreply.github.com>
=> Created code for diamond pattern in Python

ReverseOfArr.py
Signed-off-by: Razor-5 <116114456+Razor-5@users.noreply.github.com>
=> Created code for reversal of array in python using flipud()

ImplementBST.py
Signed-off-by: Razor-5 <116114456+Razor-5@users.noreply.github.com>
=> Created code to implement BST in Python

BinarySearchTree.c, Linked List/DLinkedList.c
You have assigned me the task of uploading bat using c programming after ihave created an issue. Hence I am pulling a request with changes.
govind123.ga@gmail.com
=> Binary Search tree using C

Calculator.java
Signed-off-by: HIGHINTERN <106991743+HIGHINTERN@users.noreply.github.com>
=> Created calculator in  java

insertion_sort.c
Signed-off-by: Punit Soni <109447990+punitsoni22@users.noreply.github.com>
=> hacktoberfest

SinglyLinkedList.c
The Data Structure used here is a singly linked List.
Here instead of using a predefined linked list, I have used user input system of linked list 
in which the linked list need not to be predefined and the user can create a linked list and 
add new nodes to the linked list at the front, rear or any position and can also remove nodes 
from the front, rear or any position of the linked list.
Signed-off-by: HARIKRISHNAN U S <108210868+HKRcodes@users.noreply.github.com>
=> Singly Linked List with user input

Reverse.java
Make a linked list with user input and then reverse the linked list the code is in java.
Signed-off-by: IshitaJain <91709949+ishita126jain@users.noreply.github.com>
=> Reverse linked list in java

Longest_Common_Subsequence.cpp
Please approve for hacktoberfest
Signed-off-by: Shreya Shankar <65847819+shreya-jpg@users.noreply.github.com>
=> Added code for Longest Common Subsequence (issue #70)

CircularQueue.java
=> added circular queue

reversepath.java
Signed-off-by: YashBANSAL4 <116385252+YashBANSAL4@users.noreply.github.com>
=> Created Reverse Path in Java

leftviewBt.java
Signed-off-by: YashBANSAL4 <116385252+YashBANSAL4@users.noreply.github.com>
=> Left view Binary Tree in Java

validParenthesis.java
Signed-off-by: YashBANSAL4 <116385252+YashBANSAL4@users.noreply.github.com>
=> valid Parenthesis in Java

subtreeDifference.Java
Signed-off-by: YashBANSAL4 <116385252+YashBANSAL4@users.noreply.github.com>
=> Subtree Difference in Java

quick_sort.c
Signed-off-by: Punit Soni <109447990+punitsoni22@users.noreply.github.com>
=> quick_sort.c hacktoberfest
